name: bukit_vista
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: 3.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/Ellipse.png
  - assets/man.png
  - assets/woman.png
  - assets/idcardM.png
  - assets/idcardW.png
  - assets/Property1.png
  - assets/Property2.png
  - assets/Property3.png
  - assets/Property4.png
  - assets/Property5.png
  - assets/Left.png
  - assets/Right.png
  - assets/bathtub.png
  - assets/fridge.png
  - assets/kitchen.png
  - assets/parking-area.png
  - assets/smart-tv.png
  - assets/swimming-pool.png


